import {Inject, Injectable} from '@angular/core';
import {HttpClient} from '@angular/common/http';
import {IUser} from '../../core/models/user.model';
import {APP_CONFIG, IAppConfig} from '../../app.config';




const connections = [{
  id: 1,

  user_name: 'Ard',
  user_surname: 'Ademi',
  user_email_address: 'ardademi96@gmail.com',
  user_password: 'dadsadsa',
  confirm_password: 'dasdasda',
  user_birthday: new Date(),
  user_phone_number: '045580638',


  user_personal_id: '1176291377',
  address_street: 'Preng Doci',
  address_city: 'Prishtine',
  address_country: 'Kosova',
  user_profile_image: '../../../assets/user_placeholder.png',
  user_last_travel_date: new Date(),
  user_terms_agreement: true,



  is_loading: false,
  has_been_changed: false,
  change_message: 'Ju keni thene qe keni takuar Filan Fistekun'

},
  {
    id: 2,
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: 3,
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: 4,
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: 5,
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: 6,
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: 7,
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
];
const myFamily = [{
  id: 1,

  user_name: 'Ard',
  user_surname: 'Ademi',
  user_email_address: 'ardademi96@gmail.com',
  user_password: 'dadsadsa',
  confirm_password: 'dasdasda',
  user_birthday: new Date(),
  user_phone_number: '045580638',


  user_personal_id: '1176291377',
  address_street: 'Preng Doci',
  address_city: 'Prishtine',
  address_country: 'Kosova',
  user_profile_image: '../../../assets/user_placeholder.png',
  user_last_travel_date: new Date(),
  user_terms_agreement: true,
  is_loading: false,
  has_been_changed: false,
  change_message: 'Ju keni thene qe keni takuar Filan Fistekun'

},
  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },  {
    id: Math.random(),
    user_name: 'Ard',
    user_surname: 'Ademi',
    user_email_address: 'ardademi96@gmail.com',
    user_password: 'dadsadsa',
    confirm_password: 'dasdasda',
    user_birthday: new Date(),
    user_phone_number: '045580638',
    user_personal_id: '1176291377',
    address_street: 'Preng Doci',
    address_city: 'Prishtine',
    address_country: 'Kosova',
    user_profile_image: '../../../assets/user_placeholder.png',
    user_last_travel_date: new Date(),
    user_terms_agreement: true,
    is_loading: false,
    has_been_changed: false,
    change_message: 'Ju keni thene qe keni takuar Filan Fistekun',
    response_color: ''

  },
];

@Injectable({
  providedIn: 'root'
})
export class ConnectionService {

  constructor(
    private http: HttpClient,
    @Inject(APP_CONFIG) private config: IAppConfig
  ) { }
  // TODO:Implement Connection Service
  getConnections() {
    return this.http.get<IUser[]>(this.config.apiEndpoint + '/api/v1/users/' + localStorage.getItem('userId') + '/myConnections/detail/false');
  }
  getFamily() {
    return this.http.get<IUser[]>(this.config.apiEndpoint + '/api/v1/users/' + localStorage.getItem('userId') + '/myConnections/detail/true');
  }
  deleteConnectionById() {}
  deleteFamilyMemberById() {}
}
